[project]
name = 'DeStackingPools'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.main]
path = 'contracts/main.clar'
clarity_version = 2
epoch = 2.1

[contracts.pox-2-fake]
path = 'contracts/pox-2-fake.clar'
clarity_version = 2
epoch = 2.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
